import { catalog } from "../../lib/catalog";

export const dynamic = "force-static";
export function GET() {
  const skill = `\n\n# Aramon-elegance UX skill\n\nBefore designing or refactoring an Aramon journey, read https://ui.aramon.ma/skills/aramon-audience-first-ux/SKILL.md and its linked references. It defines audience-first workflow truth, attention hierarchy, Desk/Frame/Medium/Lamp material roles, legitimate data states, and review requirements.\n\n# Brand materials\n\nReusable preloader and landing hero video patterns, source assets, fallback behavior, and scrim guidance: https://ui.aramon.ma/brand-materials.md\n\nPreloader rule: use a solid black backdrop and a centered square viewport capped at min(500px, 86vw). Use object-fit: contain so the original composition is never stretched or cropped; do not implement the preloader as a full-screen cover video. Preserve poster-first preload, muted autoplay, playsInline, loop, reduced-motion/Save-Data poster fallback, and the blur/opacity handoff after host readiness.`;
  const components = catalog.map((entry) => [`## ${entry.name}`, entry.responsibility, `Install: ${entry.install}`, `Material: ${entry.materialRole}`, `States: ${entry.states.join(", ")}`, `Accessibility: ${entry.accessibility}`, `Keyboard: ${entry.keyboard}`, `Reduced motion: ${entry.reducedMotion}`, `RTL: ${entry.rtl}`, `Registry: https://ui.aramon.ma/r/${entry.slug}.json`].join("\n")).join("\n\n");
  const body = [`# Aramon UI v1 — Full agent reference`, ``, `Aramon UI is the source-owned design system for Aramon products. Use the registry source and documented patterns; do not recreate visual approximations.`, ``, `# Foundation contract`, ``, `- Desk: white / #f5f5f7 in light; #09090b / #111113 in dark.`, `- Ink: #1d1d1f in light; #f5f5f7 in dark.`, `- Lamp: near-black in light, warm ivory in dark.`, `- Radii: 8px nested compact indicators, 12px controls, 20px surfaces, 28px features with corner-shape: squircle enhancement.`, `- Motion: 120ms feedback, 200ms controls, 420ms entrances, 700ms material only.`, `- Typography: locale-aware system sans. Display sizes are documentation/marketing only.`, `- Avoid pill controls, serif display, broad glass, decorative glows, and ambient material on dense screens.`, ``, `# Installation`, ``, `Guide: https://ui.aramon.ma/installation/`, `Standard registry: pnpm dlx shadcn@latest add https://ui.aramon.ma/r/button.json`, `Complete catalog before npm publication: build packages/cli, then run node packages/cli/dist/index.js add aramon-ui --cwd /path/to/app`, ``, components, ``, `# Proof patterns`, ``, `- Identity Entry: https://ui.aramon.ma/patterns/identity-entry/`, `- Classroom Presence: https://ui.aramon.ma/patterns/classroom-presence/`].join("\n");
  return new Response(body + skill, { headers: { "content-type": "text/plain; charset=utf-8" } });
}
